import pandas as pd
from sqlalchemy.orm import Session
from app.database.schema import FactSales, FactFinance, FactHR, FactMarketing, FactOperations, DimCustomer, DimRegion

class InsightsEngine:
    def __init__(self, db: Session):
        self.db = db

    def generate_insights(self) -> list:
        insights = []

        sales_df = pd.read_sql("SELECT * FROM fact_sales", self.db.bind)
        hr_df = pd.read_sql("SELECT * FROM fact_hr", self.db.bind)
        mkt_df = pd.read_sql("SELECT * FROM fact_marketing", self.db.bind)
        ops_df = pd.read_sql("SELECT * FROM fact_operations", self.db.bind)
        reg_df = pd.read_sql("SELECT * FROM dim_region", self.db.bind)

        # 1. Regional Profitability Margin Gap
        if not sales_df.empty and not reg_df.empty:
            sales_reg = sales_df.merge(reg_df, left_on="region_id", right_on="region_id")
            reg_agg = sales_reg.groupby("region_name").agg({"revenue": "sum", "profit": "sum"}).reset_index()
            reg_agg["margin"] = (reg_agg["profit"] / reg_agg["revenue"] * 100.0).round(1)
            
            lowest_margin_row = reg_agg.sort_values("margin").iloc[0]
            highest_rev_row = reg_agg.sort_values("revenue", ascending=False).iloc[0]

            insights.append({
                "id": "INS-001",
                "category": "Sales & Regional Strategy",
                "title": f"Regional Margin Disparity in {lowest_margin_row['region_name']}",
                "finding": f"{lowest_margin_row['region_name']} generates significant revenue (${lowest_margin_row['revenue']:,.0f}) but operates at the lowest profit margin ({lowest_margin_row['margin']}%).",
                "evidence": f"Total profit margin in {lowest_margin_row['region_name']} is {lowest_margin_row['margin']}% compared to top region {highest_rev_row['region_name']} margin of {reg_agg['margin'].max()}%.",
                "business_impact": "High revenue volume with squeezed margins erodes overall corporate profitability and inflates regional fulfillment costs.",
                "recommended_action": "Review local discounting policies, optimize logistics contracts, and reprioritize high-margin Enterprise product lines."
            })

        # 2. Marketing Channel ROI Efficiency
        if not mkt_df.empty:
            ch_agg = mkt_df.groupby("channel").agg({
                "campaign_cost": "sum",
                "revenue_generated": "sum",
                "customers_acquired": "sum"
            }).reset_index()

            ch_agg["roi"] = ((ch_agg["revenue_generated"] - ch_agg["campaign_cost"]) / ch_agg["campaign_cost"] * 100.0).round(1)
            ch_agg["cac"] = (ch_agg["campaign_cost"] / ch_agg["customers_acquired"]).round(2)

            best_roi = ch_agg.sort_values("roi", ascending=False).iloc[0]
            worst_roi = ch_agg.sort_values("roi").iloc[0]

            insights.append({
                "id": "INS-002",
                "category": "Marketing ROI",
                "title": f"{best_roi['channel']} Outperforms with {best_roi['roi']}% Marketing ROI",
                "finding": f"{best_roi['channel']} delivers the highest return on ad spend, acquiring customers at CAC of ${best_roi['cac']} vs {worst_roi['channel']} CAC of ${worst_roi['cac']}.",
                "evidence": f"Total revenue generated by {best_roi['channel']} is ${best_roi['revenue_generated']:,.0f} against campaign spend of ${best_roi['campaign_cost']:,.0f}.",
                "business_impact": "Sub-optimal budget allocation across low-performing channels reduces prospective ARR growth velocity.",
                "recommended_action": f"Reallocate 20% of marketing budget from {worst_roi['channel']} into scaling high-yield {best_roi['channel']} campaigns."
            })

        # 3. Departmental Attrition Risk
        if not hr_df.empty:
            dept_hr = hr_df.groupby("department").agg({
                "employee_id": "count",
                "attrition_status": lambda x: (x == "Yes").sum(),
                "productivity_score": "mean",
                "training_hours": "mean"
            }).reset_index()
            dept_hr.columns = ["department", "total", "churned", "avg_prod", "avg_training"]
            dept_hr["attrition_rate"] = (dept_hr["churned"] / dept_hr["total"] * 100.0).round(1)

            worst_dept = dept_hr.sort_values("attrition_rate", ascending=False).iloc[0]

            insights.append({
                "id": "INS-003",
                "category": "Human Capital",
                "title": f"Elevated Attrition Rate ({worst_dept['attrition_rate']}%) in {worst_dept['department']}",
                "finding": f"The {worst_dept['department']} department exhibits an attrition rate of {worst_dept['attrition_rate']}%, noticeably higher than the company benchmark.",
                "evidence": f"{worst_dept['churned']} out of {worst_dept['total']} staff members churned. Average annual training hours stand at {worst_dept['avg_training']:.1f} hours.",
                "business_impact": "High turnover increases talent acquisition costs and creates operational disruption in client delivery.",
                "recommended_action": f"Implement structured career development plans and increase training allocation for {worst_dept['department']} staff by 15 hours per quarter."
            })

        # 4. Operational SLA Compliance Bottlenecks
        if not ops_df.empty:
            ops_total = len(ops_df)
            sla_breached = (ops_df["sla_status"] == "Breached").sum()
            breach_pct = round((sla_breached / ops_total * 100.0), 1)

            insights.append({
                "id": "INS-004",
                "category": "Operations & Logistics",
                "title": f"SLA Breach Rate currently at {breach_pct}%",
                "finding": f"{sla_breached:,} out of {ops_total:,} orders exceeded standard fulfillment and delivery SLA time windows.",
                "evidence": f"Average order fulfillment time was {ops_df['fulfillment_time'].mean():.1f} hours, with delivery averaging {ops_df['delivery_time'].mean():.1f} days.",
                "business_impact": "Logistical delays lower customer satisfaction (CSAT) scores and increase customer churn likelihood.",
                "recommended_action": "Automate order picking in regional warehouses and renegotiate last-mile courier SLA benchmarks."
            })

        return insights
